// Service: ScriptService
// CRUD + Playwright TypeScript code generation from recorded steps

import { testLabStorage } from '../storage/TestLabStorage';
import { Script, CreateScriptDto, UpdateScriptDto, RecordedStep } from '../models/Script';

export class ScriptService {

    async list(projectId: string): Promise<Script[]> {
        return testLabStorage.listScripts(projectId);
    }

    async get(projectId: string, scriptId: string): Promise<Script | null> {
        return testLabStorage.getScript(projectId, scriptId);
    }

    async create(projectId: string, dto: CreateScriptDto): Promise<Script> {
        return testLabStorage.createScript(projectId, dto);
    }

    async update(projectId: string, scriptId: string, dto: UpdateScriptDto): Promise<Script | null> {
        return testLabStorage.updateScript(projectId, scriptId, dto);
    }

    async delete(projectId: string, scriptId: string): Promise<boolean> {
        return testLabStorage.deleteScript(projectId, scriptId);
    }

    /**
     * Generates Playwright TypeScript code from an array of recorded steps.
     * Called by RecorderService when saving a session.
     */
    generatePlaywrightTs(scriptName: string, steps: RecordedStep[]): string {
        const lines: string[] = [
            `// Auto-generated by TestFlow Test Lab Recorder`,
            `// Generated: ${new Date().toISOString()}`,
            `// Steps: ${steps.length}`,
            ``,
            `import { test, expect } from '@playwright/test';`,
            ``,
            `test('${this.sanitizeName(scriptName)}', async ({ page }) => {`,
        ];

        for (const step of steps) {
            switch (step.action) {
                case 'navigate':
                    lines.push(`  await page.goto('${step.url || ''}');`);
                    break;
                case 'click':
                    if (step.selector) {
                        lines.push(`  await page.click('${this.escapeSelector(step.selector)}');`);
                    }
                    break;
                case 'type':
                    if (step.selector && step.value !== undefined) {
                        // Preserve variable placeholders like {{email}}
                        const val = step.value.startsWith('{{')
                            ? `process.env.${step.value.replace(/[{}]/g, '').toUpperCase()} || '${step.value}'`
                            : `'${step.value.replace(/'/g, "\\'")}'`;
                        lines.push(`  await page.fill('${this.escapeSelector(step.selector)}', ${val});`);
                    }
                    break;
                case 'scroll':
                    lines.push(`  await page.evaluate(() => window.scrollBy(0, 300));`);
                    break;
                case 'hover':
                    if (step.selector) {
                        lines.push(`  await page.hover('${this.escapeSelector(step.selector)}');`);
                    }
                    break;
                case 'assert':
                    if (step.selector) {
                        lines.push(`  await expect(page.locator('${this.escapeSelector(step.selector)}')).toBeVisible();`);
                    }
                    break;
                default:
                    lines.push(`  // Unknown action: ${step.action}`);
            }
        }

        lines.push(`});`);
        return lines.join('\n');
    }

    private sanitizeName(name: string): string {
        return name.replace(/'/g, "\\'").replace(/\n/g, ' ');
    }

    private escapeSelector(sel: string): string {
        // Convert Selenium IDE selectors to Playwright format
        if (sel.startsWith('id=')) return `#${sel.slice(3)}`;
        if (sel.startsWith('css=')) return sel.slice(4);
        if (sel.startsWith('name=')) return `[name="${sel.slice(5)}"]`;
        if (sel.startsWith('xpath=')) return `xpath=${sel.slice(6)}`;
        if (sel.startsWith('linkText=')) return `text=${sel.slice(9)}`;
        return sel.replace(/'/g, "\\'");
    }
}

export const scriptService = new ScriptService();
